### ISSUE TITLE
React Hooks and DT

### ISSUE THREAD

**Issue by AllStackDev1** [donatso/family-chart#1]
It is hard to make use of functionalities in react, having a react hook will go a long way. 
I want to be able to create forms in react, currently had to make use of your js example form.
A types declarations would also be helpful for typescript.

**Comment by donatso** [comment]
hi @AllStackDev1,
yes, react doesn't like when you do dom manipulation by yourself. In next versions of family-chart I will provide more solutions for that with concrete examples in read.me.
I will see what I can do for you typescript users as well :)
