### ISSUE TITLE
Custom elements

### ISSUE THREAD

**Issue by rbb-soft** [donatso/family-chart#11]
Hello Donatso, I would like to use my last wish :).
I tried to use the custom element but failed miserably.

Could you post a working example?

From already thank you very much

**Comment by donatso** [comment]
you keep reminding me that I need to do more work on this project :smile: .. I will have to do that before I can give you good solution.

**Comment by therahulsarkar** [comment]
Hello, @donatso 
We are also trying to implement the onclick event on the card so that more details can be displayed with either mouse hover or with onclick, but can't find any solution to implement this feature. Is there any update regarding this? I'm working on a project that needs this feature asap!

I'd love to hear any update regarding the features. Eagerly waiting for your response.

**Comment by trots** [comment]
> Hello Donatso, I would like to use my last wish :). I tried to use the custom element but failed miserably.
> 
> Could you post a working example?
> 
> From already thank you very much

[This example](https://github.com/trots/family-chart-details-form) can help.

**Comment by rbb-soft** [comment]
> > Hello Donatso, I would like to use my last wish :). I tried to use the custom element but failed miserably.
> > Could you post a working example?
> > From already thank you very much
> 
> [This example](https://github.com/trots/family-chart-details-form) can help.

work great.......... thank you.

maybe Donat Soric can include this feature in next release

**Comment by rbb-soft** [comment]
> > Hello Donatso, I would like to use my last wish :). I tried to use the custom element but failed miserably.
> > Could you post a working example?
> > From already thank you very much
> 
> [This example](https://github.com/trots/family-chart-details-form) can help.

work great.......... thank you.

maybe Donat Soric can include this feature in next release
