### ISSUE TITLE
Search and Image

### ISSUE THREAD

**Issue by SAFWorld** [donatso/family-chart#13]
Hello Donatso,

I really loved your project and i have started to build one with my lineage. While working on it, i came across few scenarios, looking for your help around this...  

1. Can you help implement Search option on the chart!! 
2. I am also trying to implement onclick event on Image so that the Image would blow up for better visibility. 
3. Click on card to show more details..
4. Can we count the number of nodes excluding the hidden ones!!
5. Minimize larger nodes by default.

**Comment by donatso** [comment]
I will need to find time to help you with that. Not sure if I will be able to do it this week.

**Comment by therahulsarkar** [comment]
Hello, @donatso
We are also trying to implement the onclick event on the card so that more details can be displayed with either mouse hover or with onclick, but can't find any solution to implement this feature. Is there any update regarding this? I'm working on a project that needs this feature asap! 

I'd love to hear any update regarding the features. Eagerly waiting for your response.

**Comment by SAFWorld** [comment]
Hello Donatso,

Were you able to fetch some time for solution!! Eagerly waiting

**Comment by SAFWorld** [comment]
Hello Donatso,

Were you able to get some time to create search feature

**Comment by donatso** [comment]
Hi,
There is the new version of family-chart and here is the link for search implementation:
https://donatso.github.io/family-chart-doc/examples/9-big-tree

**Comment by SAFWorld** [comment]
Thank you very much... I was waiting eagerly for your reply :)

**Comment by donatso** [comment]
Yes, it is uploaded in a separate project that I use for examples.
On the link that I posted above you have full html code below where you can see the complete code for it.

**Comment by SAFWorld** [comment]
Yes, i was able to find it.. this is a separate project.. i was searching
in the old project.

Really appreciate it, how you have done it. I love you project :)  Will
there be anything on React as well like older project?

And wanted to check with another query that i had mentioned:
- 1. Implement onclick event on Image so that the Image would blow up for
better visibility - i found an example - but wanted to know if we can add
kind of gallery so that we can move two or three photos
- 2. Click on card to show more details - hope u understand - Date of
birth, place of birth, Father, mother, etc..
- 3. Can we count the number of nodes for the selected one - it would mean,
they have soo many Children, Grand Children :)

Hope i am not asking too much... but i guess this would be wonderful and
everyone would love it :)

Again, thank you for this project

**Comment by SAFWorld** [comment]
Hello,

Wanted to check with you, if I want to create a login page which approach
would be good? React or vue? Or anything else..

Regards

**Comment by SAFWorld** [comment]
Hello Donatso

Please let me know if its possible?

Regards

**Comment by SAFWorld** [comment]
Hello,

Any update on this ? If you could give me tips then i can try..

**Comment by SAFWorld** [comment]
Hello,

Hope you are doing good... were you able to update it? Eagerly waiting for
your reply..
