### ISSUE TITLE
How to perform clean up in useEffect

### ISSUE THREAD

**Issue by AllStackDev1** [donatso/family-chart#2]
so when I use state to toggle between views, it crashes when I try mounting back a tree component, works the first time but going back I get this.
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/36667083/150834180-8756a773-e897-4717-805f-6ea0fbbf4bc1.png">
Need a way to clean up when unmounting.

**Comment by donatso** [comment]
It seems that your family tree json is corrupted. I am not sure what is causing it. Can you try to isolate the problem?

**Comment by AllStackDev1** [comment]
So what i figured out was that the tree overwrite the source json data. so
i try to not make a direct reference to it, using
json.parse(json.stringfy(data)). it solved it. thanks
