### ISSUE TITLE
This error is constantly showing up in my application, Failed to read the 'value' property from 'SVGLength': Could not resolve relative length

### ISSUE THREAD

**Issue by kumar-abhinit** [donatso/family-chart#20]
![SVGLengtherror](https://user-images.githubusercontent.com/78499679/208309621-1a163891-f90e-43a0-bee2-8d98020a0524.png)

**Comment by donatso** [comment]
It seems that it is something specific to your implementation, but I cannot guess what it is

**Comment by kumar-abhinit** [comment]
is that so?, i will re-check and revert

**Comment by kumar-abhinit** [comment]
Yeah, It's solved, thanks for the support

**Comment by isswarya-ideassion** [comment]
@kumar-abhinit  Hi can you tell us what was causing the above error. I'm also facing it
