### ISSUE TITLE
Using family-chart with Laravel 10 Vite + React 

### ISSUE THREAD

**Issue by majster-pl** [donatso/family-chart#28]
Hi, I'm working on family tree in my spare time and I come across your package which would work perfect for me but I having issue using it with above combination.
I wonder if you'll be able to help me resolve the problem?

When importing f3 as in your React example 
`import f3 from "family-chart"; // npm i family-chart`
I get error:
`[plugin:vite:import-analysis] Failed to resolve entry for package "family-chart". The package may have incorrect main/module/exports specified in its package.json.`

I've asked for help laravel community but none of the suggestions worked so I thought I'll reach out to you.
Here is a link to post in laracasts forum. 
[https://laracasts.com/discuss/channels/vite/laravel-10-vite-react-problem-importing-npm-packages](url)

Regards.

**Comment by ed-fruty** [comment]
Found this library and got the same error during the first try. 
So the fix is to change import path to the full one:

```js
import f3 from "family-chart/dist/family-chart";
```
