### ISSUE TITLE
Multi Line Support

### ISSUE THREAD

**Issue by Vanshbordia** [donatso/family-chart#3]
I tried adding another tspan in the js file but it doesn't seem to render the third line. Is there something I am missing / can it be added as a feature?

**Comment by donatso** [comment]
Yes, it seems that I fixed it to 2 tspans. Below is a quick fix for that, but in the future I will provide better solution :)

In this example (https://codesandbox.io/s/family-chart-static-multiline-card-label-hxqqwe?file=/index.html) you can see cardDisplayMultiLine function that will help you create multi line card label. Hope it works out for you.
