### ISSUE TITLE
Performance issues on large dataset

### ISSUE THREAD

**Issue by bobokeke0** [donatso/family-chart#4]
Is there a way to handle rendering a very large family tree? It seem to choke and the interaction is very very slow.

**Comment by bobokeke0** [comment]
maybe there's a way to render portions of the tree and render the rest as they are expanded?

**Comment by donatso** [comment]
hmm, I am not sure how big the tree have to be. This one is pretty big, but it work ok, I think.. https://donatso.github.io/family-chart/examples/wiki-tree/?wiki_id=Q855
Can you give me some example of that very large tree?

**Comment by bobokeke0** [comment]
sorry for the late reply. The example you showed seem to have less than 50 nodes (individual names). I'm looking to render a tree with almost 1000 nodes.

**Comment by bobokeke0** [comment]
Haha yeah. This took is amazing but I'm pushing it with that many nodes.

That's perfect. Cutting the tree before rendering actually give a better experience. Thanks a million!!
