### ISSUE TITLE
Can we set showing generations from left to right instead of top to bottom? 

### ISSUE THREAD

**Issue by mkay905** [donatso/family-chart#47]
How to set the layout of chart from right to left, showing ancestors on left and desendant on right side.

**Comment by donatso** [comment]
this feature in implemented in v0.2.1
https://donatso.github.io/family-chart-doc/examples/13-horizontal-tree
I added it in create-tree configuration as well https://donatso.github.io/family-chart-doc/create-tree

**Comment by mkay905** [comment]
Thanks..It really helps.
