### ISSUE TITLE
Can you add the ability to have a single parent and a line down from them?

### ISSUE THREAD

**Issue by joeghartey** [donatso/family-chart#49]
Can you add the ability to have a single parent and a line down from them?  It would make it much easier for single mothers who use invetreo or would rather reflect themselves as a single mother.  It would also help the child, by not having to look at anb "unknown" box for their father
Thanks

**Comment by mustela** [comment]
We would also love to have this feature. Is there any plan to add it currently? If there is interest in having it, we could help by submitting a pull request.

**Comment by donatso** [comment]
Feature is added in v0.2.0
Here is a link in examples: https://donatso.github.io/family-chart-doc/examples/12-single-parent
It is available in configuration for create-tree as well: https://donatso.github.io/family-chart-doc/create-tree

**Comment by mustela** [comment]
@donatso awesome, thanks a lot!!!
