### ISSUE TITLE
Is there a way to distinguish relationships?

### ISSUE THREAD

**Issue by SDVII** [donatso/family-chart#7]
First of all, thanks for the incredible effort.
Let's say that I would like to show divorced couples with a dashed relationship line, is that possible?
Thanks again for your time

**Comment by donatso** [comment]
Hi,
Thats a good point, and something I should probably include in the future, 
but unfortunately I don't know any quick fix that can help you right now :/

**Comment by SDVII** [comment]
Alright, thanks for the response
