### ISSUE TITLE
zoom in on a certain card

### ISSUE THREAD

**Issue by rbb-soft** [donatso/family-chart#9]
this is the second query i make, is it possible to zoom to a particular card.

Thank you very much in advance and so that there is a certain reciprocity I am going to collaborate with a way to use your library in angular

https://codesandbox.io/s/ng-family-chart-cjh8sf?file=/src/app/app.component.ts

**Comment by donatso** [comment]
No problem rbb, you have one more wish :)

Here is tweak to your code: https://codesandbox.io/s/ng-family-chart-forked-qjn6ss?file=/src/app/app.component.ts
And here is in static version: https://codesandbox.io/s/family-chart-static-zoom-to-card-djd2mw?file=/index.html
